name: "Build docs-atlassian-remote"

run-name: "Build docs-atlassian-remote: ${{ github.event.inputs.tag || github.run_number }}"

on:
  push:
    branches:
    - develop

  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify tag (ex. rc5) or it will be set automaticaly :rc<run_number>'
        type: string
        required: false

env:
  DOCKER_HUB_IMAGE_NAME: docs-atlassian-remote
  DOCKER_HUB_NAMESPACE: onlyoffice

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: handle-rc-tag
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref_name }}
          MANUAL_TAG: ${{ github.event.inputs.tag }}
        run: |
          echo "APP_VERSION=$()" >> "$GITHUB_ENV" # Should be set!
          if [[ "$EVENT" == 'push' && "$REF" == 'develop' ]]; then
           echo "RC_TAG=rc${{ github.run_number }}" >> "$GITHUB_ENV"
          elif [[ "$EVENT" == 'workflow_dispatch' && -z "$TAG" ]]; then
           echo "RC_TAG=rc${{ github.run_number }}" >> "$GITHUB_ENV"
          fi

      - name: Publish Image
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_HUB_NAMESPACE }}/docs-atlassian-remote:${{ env.APP_VERSION }}-${{ github.event.inputs.tag || env.RC_TAG }}
